name: Build Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: install dependencies
        run: npm i --force

      - name: Install Capacitor
        run: npm install -D @capacitor/cli @capacitor/assets

      - name: Build Vue App
        run: npm run build

      - name: Add android folder if not present
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor sync
        run: npx cap sync
       
      - name: Generate icons and splash screen
        run:  if [ -d "./resources" ]; then npx capacitor-assets generate --splashBackgroundColor '#FDFDF6' --splashBackgroundColorDark '#1A1C18' --android; fi
        
      - name: Gradle build APK
        run: cd android && ./gradlew assembleDebug
        
      - name: Generate debug.keystore
        run: |
         keytool -genkey -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        
      - name: Sign debug build
        run: jarsigner -keystore android/app/debug.keystore -storepass android -keypass android -digestalg SHA1 -sigalg MD5withRSA -signedjar ./android/app/build/outputs/apk/debug/app-debug-signed.apk ./android/app/build/outputs/apk/debug/app-debug.apk androiddebugkey

      - name: Verify signed APK
        run: jarsigner -verify -verbose -certs ./android/app/build/outputs/apk/debug/app-debug-signed.apk

      - name: Move signed APK to proper location
        run: mv ./android/app/build/outputs/apk/debug/app-debug-signed.apk ./android/app/build/outputs/apk/debug/app-debug.apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/app-debug.apk